### ISSUE TITLE
[bug] isEmpty / isNotEmpty failing when passing an undefined value

### ISSUE THREAD

**Issue by ngarbezza** [ngarbezza/testy#125]
**Describe the bug**

`isEmpty` and `isNotEmpty` are failing when passing an undefined value. Instead of a failure, it's throwing an error.

**To Reproduce**

1. Run this suite:

```js
suite('isEmpty / isNotEmpty bug', () => {
  test('isEmpty throwing error instead of failure', () => {
    assert.isEmpty(undefined);
  });
  
  test('isNotEmpty throwing error instead of failure', () => {
    assert.isNotEmpty(undefined);
  });
});
```

2. Observe errors instead of failures:

```
Failures summary:

[ERROR] isNotEmpty throwing error instead of failure
  => TypeError: Cannot convert undefined or null to object

[ERROR] isEmpty throwing error instead of failure
  => TypeError: Cannot convert undefined or null to object
```

**Expected behavior**
A failure with message `expected undefined to be empty` / `expected undefined to be not empty`

**Comment by abraaoduarte** [comment]
I would like work in that bug

**Comment by abraaoduarte** [comment]
PR #131 131

**Comment by ngarbezza** [comment]
Thank you! Will be included in the next release :tada:
