### ISSUE TITLE
[bug] includes() and doesNotInclude() matchers only work on Arrays

### ISSUE THREAD

**Issue by ngarbezza** [ngarbezza/testy#130]
**Describe the bug**
The `includes()` and `doesNotInclude()` matchers do not work when the object under test is not an Array, but it is still an iterable (map, set, string).

**Version(s) affected**
v5.0.1

**To Reproduce**

Run the following test and watch it fail:

```javascript
test('includes works with Sets', () => {
    asserter.that(new Set([42])).includes(42);
  
    expectSuccess();
  });
```

**Expected behavior**
The above test should pass, and the same with Map and String objects. And the opposite behavior with `doesNotInclude()`.

**Additional context**
The problem is that the matchers are using the `find` function with only works with arrays

**Comment by abraaoduarte** [comment]
I would like work in that bug

**Comment by trochepablo** [comment]
> I would like work in that bug

Hello @abraaoduarte can you leave me this issue? is for my fist issue for the university.

**Comment by abraaoduarte** [comment]
> > I would like work in that bug
> 
> Hello @abraaoduarte can you leave me this issue? is for my fist issue for the university.

Sure. You can get this issue.

**Comment by trochepablo** [comment]
> > > I would like work in that bug
> > 
> > 
> > Hello @abraaoduarte can you leave me this issue? is for my fist issue for the university.
> 
> Sure. You can get this issue.

Muito obrigado!

**Comment by trochepablo** [comment]
> **Describe the bug**
> The `includes()` and `doesNotInclude()` matchers do not work when the object under test is not an Array, but it is still an iterable (map, set, string).
> 
> **Version(s) affected**
> v5.0.1
> 
> **To Reproduce**
> 
> Run the following test and watch it fail:
> 
> ```js
> test('includes works with Sets', () => {
>     asserter.that(new Set([42])).includes(42);
>   
>     expectSuccess();
>   });
> ```
> 
> **Expected behavior**
> The above test should pass, and the same with Map and String objects. And the opposite behavior with `doesNotInclude()`.
> 
> **Additional context**
> The problem is that the matchers are using the `find` function with only works with arrays

Please, can you assign to me this issue?

Regards!
