### ISSUE TITLE
[feature] after() hook

### ISSUE THREAD

**Issue by ngarbezza** [ngarbezza/testy#135]
**Is your feature request related to a problem? Please describe.**
Sometimes we might need to do something after a test ends, like releasing a resource we grabbed in a `before()`. 

**Describe the solution you'd like**

* An `after(func)` hook working in a similar way to `before(func)`. Cannot be defined twice in the same suite.
* `after()` is evaluated right after the execution of a test, no matter the result of it (pass, failure, error)

**Comment by adico1** [comment]
i'll take this one

**Comment by ngarbezza** [comment]
This done! Thank you for the contribution!
