### ISSUE TITLE
[bug] suite and test names cannot be empty

### ISSUE THREAD

**Issue by ngarbezza** [ngarbezza/testy#136]
**Describe the bug**
It is possible to create suites and tests with empty names

**Version(s) affected**
v5.0.1

**To Reproduce**

Run the following suite/test and watch it pass:

```javascript
suite('', () => {
  test('', () => {
    assert.that(undefined).isUndefined();
  });
});
```

**Expected behavior**
Testy should fail (not executing the suite because it is considered invalid), and display a descriptive error message, like `'Suite and test names cannot be empty'`.

**Comment by ask-imran** [comment]
I would love to give this a go.! can I have it assigned to me?

**Comment by ngarbezza** [comment]
@ask-imran sure, it's all yours!

**Comment by ngarbezza** [comment]
Completed! #153
