### ISSUE TITLE
[bug] validate argument types of test()

### ISSUE THREAD

**Issue by ngarbezza** [ngarbezza/testy#137]
**Describe the bug**
Any type of object can be passed as the first argument to `test()`. This object is printed in the console giving a potential weird output.

The same occurs with the second argument, if it is not a function, the test fails due to a testy error trying to call an object that is not a function.

**Version(s) affected**
v5.0.1

**To Reproduce**

Run the following and watch it pass:

```javascript
suite('suite', () => {
  test(['a', 'test'], 'hey');
});
```

**Expected behavior**
Tests should be validated in the same way as suites, there's already a validation on the name and body of suites, it needs to be replicated here.

**Comment by adico1** [comment]
i can take that

**Comment by ngarbezza** [comment]
This is now merged!
