### ISSUE TITLE
[feature] Warning message to display when no tests found

### ISSUE THREAD

**Issue by ngarbezza** [ngarbezza/testy#157]
**Is your feature request related to a problem? Please describe.**
When running tests w/o arguments (like running `npm test`) and no tests match the filter specified (`_test.js` by default) the output says there are no tests but it might be confusing for people using the tool for the first time and we can provide some education about how to name the test files. 

**Describe the solution you'd like**
A warning message (probably in yellow color?) to indicate something like "Make sure your files matches the XXXX naming filter", where XXXX is the actual value of the filter configuration.

**Comment by niyonx** [comment]
Hi, I am working on it!
