### ISSUE TITLE
[feature] error message when requested file/folder is not valid

### ISSUE THREAD

**Issue by ngarbezza** [ngarbezza/testy#158]
**Is your feature request related to a problem? Please describe.**
Running `npm test file_or_folder_not_found` fails with an internal node message.

**Describe the solution you'd like**
Handle that error and display an error message, in red, to indicate the requested file/folder does not exist. If we have multiple files or folders requested, it's fine if we fail in the first one we found (it's not necessary to collect all the failures). We need to make sure the exit code is 1.

**Comment by chelsieng** [comment]
I'm on it! :)

**Comment by ngarbezza** [comment]
this is done!
