### ISSUE TITLE
iNotEqualTo does not have expected behaviour when both parts are undefined

### ISSUE THREAD

**Issue by franciscojaimesfreyre** [ngarbezza/testy#191]
**Describe the bug**
iNotEqualTo does not have expected behavior (expecting the same a isEqualTo) when both parts, actual and expected, are undefined.
**Version(s) affected**
6.14.5

**To Reproduce**

Try running this test:

`test('isNotEqualTo fails if both parts are undefined', () => {
    const result = resultOfATestWith(assert => assert.that(undefined).isNotEqual(undefined));
    expectFailureOn(result, I18nMessage.of('equality_assertion_failed_due_to_undetermination'));
  });`

**Expected behavior**
Example test should pass, as the assertion should fail with message 'equality_assertion_failed_due_to_undetermination'.

**Comment by ngarbezza** [comment]
Thank you for reporting this! I was able to reproduce it on 5.1.0. Looks like the approach you did for #190 of returning `undefined` as the result of a `BothPartsUndefined` comparison strategy would solve the issue (we would need to think how to avoid that undefined as a result, but I think it is good for now). So if you want to fix this as well, go for it!

**Comment by franciscojaimesfreyre** [comment]
Great! I will then!

**Comment by ngarbezza** [comment]
Fixed here: #192 thank you @franciscojaimesfreyre !
