### ISSUE TITLE
[bug] failFast configuration parameter should fail if an invalid value is provided

### ISSUE THREAD

**Issue by ngarbezza** [ngarbezza/testy#203]
**Describe the bug**
It seems that it is possible to configure Testy with an invalid value for the `failFast` configuration parameter, and it does not cause a failure.

**Version(s) affected**

**To Reproduce**

Run any suite with the following configuration in `.testyrc.json`:

```json
{
  "directory": "./tests",
  "filter": ".*_test.js$",
  "language": "en",
  "failFast": "I AM AN INVALID VALUE",
  "randomOrder": true
}
```

**Expected behavior**
An error message before running any suite explaining that the provided value is not valid, and the allowed values are `true` and `false` (booleans).

**Comment by ignacio-r** [comment]
Hi! @ngarbezza could you fix this one? If not, you can assign it one to me.

**Comment by ngarbezza** [comment]
Hi @ignacio-r ! I'll assign it to you. Thank you!
