### ISSUE TITLE
[refactoring] Use syntax for private fields

### ISSUE THREAD

**Issue by ngarbezza** [ngarbezza/testy#205]
**Problem**
We're handling private fields using the `_field` convention. As this is a convention, the fields are still accessible.

**Proposed solution**
Now we can use `#field` syntax: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_With_Private_Class_Features, that is supported since Node 6, so there are no issues with introducing the syntax to this project.

The proposal is to change it across the whole codebase. We can make chunks of changes in different PRs if that's helpful.

**Comment by abhikhatri67** [comment]
Hey @ngarbezza, can I work on this issue?

**Comment by ngarbezza** [comment]
> Hey @ngarbezza, can I work on this issue?

Sure! It's all yours

**Comment by ngarbezza** [comment]
Marking the issue as blocked. See the comment here: https://github.com/ngarbezza/testy/pull/206#issuecomment-930544639

Once the class fields feature reaches the "official" ecmascript status, we can change our code and continue with this issue.
