### ISSUE TITLE
[feature] Add numeric assertions for numerical comparisons

### ISSUE THREAD

**Issue by beluamat29** [ngarbezza/testy#286]
## Is your feature request related to a problem? Please describe.

Even though numerical comparisons can be achieved using boolean assertions (like `assert.isTrue(3 < 4)`) I think is more semantically correct to have numerical assertions to compare numbers that don't involve boolean assertions i.e isLessThan, isGreaterThan, etc.

## Describe the solution you'd like

I'd be great if we can add assertions for the cases greater than, greater or equal than, less than and less or equal than

**Comment by ngarbezza** [comment]
@allcontributors please add @beluamat29 as contributor for code, tests, translations and documentation
