### ISSUE TITLE
[feature] isIncludedIn() and isNotIncludedIn() assertions

### ISSUE THREAD

**Issue by ngarbezza** [ngarbezza/testy#75]
**Is your feature request related to a problem? Please describe.**
Sometimes we want to assert that a value is or is not included in a collection. Similar to `includes()` and `doesNotInclude()` but the other way around. Should work with Array and Sets.

**Describe the solution you'd like**
* `assert.that(value).isIncludedIn(collection)`
* `assert.that(value).isNotIncludedIn(collection)`

**Comment by ask-imran** [comment]
Hi @ngarbezza,
Can I pick this up ?

**Comment by ngarbezza** [comment]
@ask-imran sure! let me assign you

**Comment by ngarbezza** [comment]
Completed! #154
